# Site settings
title: Mex Delgado - Sr. Developer Full-Stack
description: Que lo imposible, pueda ser posible
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mex Delgado
user_description: To embark on a career of achievement, with possibilities of growth by extending my professional training. To be able to apply all my theoretical knowledge to practice and thus learn to perform more and better in the digital transformation generating a positive impact on society.
user_title: Sr. Developer Full-Stack
email: mdelgado@tresdoce.com.ar
twitter_username: rudemex
github_username:  rudemex
instagram_username:  rudemex
facebook_username:  rudemex
linkedin_username:  rudemex

# Google-analytics
google-analytics:
  id: "UA-165583828-1"

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman